//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Connection_Id { get; set; }
        public Nullable<int> Connection_Left_Term_Id { get; set; }
        public Nullable<int> Connection_Right_Term_Id { get; set; }
        public string Connection_Name { get; set; }
        public string Connection_Synonym { get; set; }
        public string Connection_Time_Limitation { get; set; }
        public string Connection_Position_Limitation { get; set; }
        public Nullable<int> Connection__Amount_Limitation { get; set; }
        public string Connection_Climate_Limitation { get; set; }
        public string Connection_Season_Limitation { get; set; }
        public string Connection_Measurement { get; set; }
        public Nullable<bool> Connection_IsDelete { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual Term Term1 { get; set; }
    }
}
