//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Property_Id { get; set; }
        public Nullable<int> Property_Term_Id { get; set; }
        public string Property_Key { get; set; }
        public string Property_Value { get; set; }
    
        public virtual Term Term { get; set; }
    }
}
