//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int Relation_Id { get; set; }
        public Nullable<int> Relation_Parent_Term_Id { get; set; }
        public Nullable<int> Relation_Child_Term_Id { get; set; }
        public Nullable<bool> Relation_IsDelete { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual Term Term1 { get; set; }
    }
}
