//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlFile
    {
        public XmlFile()
        {
            this.Term = new HashSet<Term>();
        }
    
        public int XmlFile_Id { get; set; }
        public string XmlFile_Name { get; set; }
    
        public virtual ICollection<Term> Term { get; set; }
    }
}
